import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/server/Header'

export const metadata: Metadata = {
  title: 'Rick and Morty',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <div className="p-5">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
